apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 3  # work with 3 pods
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: dockerimageUrl/demo-app:1.0 
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE 
          value: "prod"
        livenessProbe:  
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe: 
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: LoadBalancer  # expose to external
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 80  # external port
      targetPort: 8080  # Container port
